const addonsData = [
  {
    appliesToTelco: 'Giga!',
    appliesToPlans: 'All',
    addonName: '1GB',
    data: 1,
    talktime: 0,
    sms: 0,
    price: 2,
    keepAdding: true,
  },
  {
    appliesToTelco: 'Circles.Life',
    appliesToPlans: ['Base Plan (New number)', 'Base Plan (Transfer number)'],
    addonName: 'Unlimited Data',
    data: 10000,
    talktime: 0,
    sms: 0,
    price: 20,
    cons: ['Usage in excess of the extra 20GB/mth may be at controlled speeds'],
    keepAdding: false,
  },
  {
    appliesToTelco: 'Singtel',
    appliesToPlans: ['Combo 2', 'Combo 3', 'Combo 6', 'Combo 12'],
    addonName: 'Data X 2',
    multiplier: true,
    data: 2,
    talktime: 1,
    sms: 1,
    price: 5.9,
    cons: ['One-time sign up fee of $10.70'],
    keepAdding: false,
  },
  {
    appliesToTelco: 'Singtel',
    appliesToPlans: ['Combo 2', 'Combo 3', 'Combo 6', 'Combo 12'],
    addonName: 'Data X 3',
    multiplier: true,
    data: 3,
    talktime: 1,
    sms: 1,
    price: 9.9,
    cons: ['One-time sign up fee of $10.70'],
    keepAdding: false,
  },
  {
    appliesToTelco: 'Singtel',
    appliesToPlans: ['Combo 2', 'Combo 3', 'Combo 6', 'Combo 12'],
    addonName: 'Data X 4',
    multiplier: true,
    data: 4,
    talktime: 1,
    sms: 1,
    price: 19.9,
    cons: ['One-time sign up fee of $10.70'],
    keepAdding: false,
  },
  {
    appliesToTelco: 'Singtel',
    appliesToPlans: ['Combo 3', 'Combo 6', 'Combo 12'],
    addonName: 'Data X INFINITY',
    multiplier: true,
    data: 10000,
    talktime: 1,
    sms: 1,
    price: 39.9,
    cons: ['One-time sign up fee of $10.70', 'Usage in excess of the extra 50GB/mth may be at controlled speeds'],
    keepAdding: false,
  },
];

export default addonsData;