const mobilePlanData = [
  {
    telco: 'Singtel',
    planName: 'XO 48',
    data: 5,
    talktime: 100,
    sms: 100,
    price: 48,
  },
  {
    telco: 'Singtel',
    planName: 'XO 78',
    data: 30,
    talktime: 300,
    sms: 300,
    price: 78,
  },
  {
    telco: 'Singtel',
    planName: 'XO 108',
    data: 50,
    talktime: 500,
    sms: 500,
    price: 108,
  },
  {
    telco: 'Singtel',
    planName: 'Combo 1',
    data: 0.1,
    talktime: 100,
    sms: 500,
    price: 27.9,
  },
  {
    telco: 'Singtel',
    planName: 'Combo 2',
    data: 2,
    talktime: 200,
    sms: 1000,
    price: 42.9,
    pros: ['2GB Singtel Wifi'],
  },
  {
    telco: 'Singtel',
    planName: 'Combo 3',
    data: 3,
    talktime: 10000,
    sms: 10000,
    price: 68.9,
    pros: ['2GB Singtel Wifi'],
  },
  {
    telco: 'Singtel',
    planName: 'Combo 6',
    data: 6,
    talktime: 10000,
    sms: 10000,
    price: 95.9,
    pros: ['2GB Singtel Wifi', '24mths HBO GO', '24mths Entertainment Plus'],
  },
  {
    telco: 'Singtel',
    planName: 'Combo 12',
    data: 12,
    talktime: 10000,
    sms: 10000,
    price: 239.9,
    pros: ['2GB Singtel Wifi', '24mths HBO GO', '24mths Entertainment Plus', '$500 yearly handset upgrade voucher', 'Free Caller-ID & AutoRoam'],
  },
  {
    telco: 'Singtel',
    planName: 'SIM Only 10GB Plan + Free extra 20GB',
    data: 30,
    talktime: 150,
    sms: 500,
    price: 36.05,
    pros: ['Unlimited Singtel Wifi', '12mths Entertainment Plus'],
    cons: ['12mths contract'],
  },
  {
    telco: 'Singtel',
    planName: 'SIM Only 5GB Plan + Free extra 10GB',
    data: 15,
    talktime: 150,
    sms: 500,
    price: 20,
    pros: ['2GB Singtel Wifi', '12mths Entertainment Plus'],
    cons: ['12mths contract'],
  },
  {
    telco: 'Singtel',
    planName: 'Silver Combo 1',
    data: 0.1,
    talktime: 100,
    sms: 500,
    price: 22.32,
    pros: ['Free voicemail'],
  },
  {
    telco: 'Singtel',
    planName: 'Silver Combo 2',
    data: 2,
    talktime: 200,
    sms: 1000,
    price: 34.32,
    pros: ['2GB Singtel Wifi', '24mths Entertainment Plus'],
  },
  {
    telco: 'Singtel',
    planName: 'Silver Combo 3',
    data: 3,
    talktime: 10000,
    sms: 10000,
    price: 55.12,
    pros: ['2GB Singtel Wifi', '24mths Entertainment Plus'],
  },
  {
    telco: 'Singtel',
    planName: 'Youth Combo 1',
    data: 0.1,
    talktime: 100,
    sms: 10000,
    price: 27.9,
    pros: ['2GB Singtel Wifi'],
  },
  {
    telco: 'Singtel',
    planName: 'Youth Combo 2',
    data: 4,
    talktime: 10000,
    sms: 10000,
    price: 42.9,
    pros: ['2GB Singtel Wifi'],
  },
  {
    telco: 'Singtel',
    planName: 'Youth Combo 3',
    data: 7,
    talktime: 10000,
    sms: 10000,
    price: 68.9,
    pros: ['2GB Singtel Wifi', '24mths Entertainment Plus'],
  },
  {
    telco: 'Singtel',
    planName: 'Youth Combo 6',
    data: 7,
    talktime: 10000,
    sms: 10000,
    price: 95.9,
    pros: ['2GB Singtel Wifi', '24mths Entertainment Plus', '24mths HBO GO'],
  },
  {
    telco: 'Circles.Life',
    planName: 'Base Plan (New number)',
    data: 20,
    talktime: 100,
    sms: 25,
    price: 28,
    pros: ['Free Caller-ID'],
  },
  {
    telco: 'Circles.Life',
    planName: 'Base Plan (Transfer number)',
    data: 20,
    talktime: 100,
    sms: 25,
    price: 18,
    cons: ['Price returns to $28/mth after 1 year'],
    pros: ['Free Caller-ID'],
  },
  {
    telco: 'Circles.Life',
    planName: '$5 Plan',
    data: 2,
    talktime: 50,
    sms: 25,
    price: 5,
    cons: ['Phones, roaming, and unlimited data are only available with 20GB Base Plan sign-ups'],
    pros: ['Free Caller-ID'],
  },
  {
    telco: 'Singtel',
    planName: 'GOMO',
    data: 20,
    talktime: 200,
    sms: 200,
    price: 20,
    pros: ['Free Caller-ID'],
  },
  {
    telco: 'Starhub',
    planName: '$50 2-year Plan',
    data: 15,
    talktime: 100,
    sms: 0,
    price: 50,
    pros: ['Free weekend data', 'Free Caller-ID', 'Free International Roaming'],
  },
  {
    telco: 'Starhub',
    planName: '$75 2-year Plan',
    data: 40,
    talktime: 300,
    sms: 0,
    price: 75,
    pros: ['Free weekend data', 'Free Caller-ID', 'Free International Roaming'],
  },
  {
    telco: 'Starhub',
    planName: '$105 2-year Plan',
    data: 70,
    talktime: 500,
    sms: 0,
    price: 105,
    pros: ['Free weekend data', 'Free Caller-ID', 'Free International Roaming'],
  },
  {
    telco: 'Starhub',
    planName: '$238 2-year Plan',
    data: 110,
    talktime: 10000,
    sms: 10000,
    price: 238,
    pros: ['Free weekend data', 'Free Caller-ID', 'Free International Roaming'],
  },
  {
    telco: 'Starhub',
    planName: '$25 SIM Only Plan',
    data: 15,
    talktime: 100,
    sms: 0,
    price: 25,
    pros: ['Free weekend data', 'Free Caller-ID', 'Free International Roaming', 'Online exclusive: $120 bill rebate'],
  },
  {
    telco: 'Starhub',
    planName: '$50 SIM Only Plan',
    data: 40,
    talktime: 300,
    sms: 0,
    price: 50,
    pros: ['Free weekend data', 'Free Caller-ID', 'Free International Roaming', 'Online exclusive: $120 bill rebate'],
  },
  {
    telco: 'Starhub',
    planName: '$80 SIM Only Plan',
    data: 70,
    talktime: 500,
    sms: 0,
    price: 80,
    pros: ['Free weekend data', 'Free Caller-ID', 'Free International Roaming', 'Online exclusive: $120 bill rebate'],
  },
  {
    telco: 'M1',
    planName: 'SIM Only Plan',
    data: 30,
    talktime: 1000,
    sms: 1000,
    price: 25,
    pros: ['Free incoming calls', 'Unlimited free calls to 3 M1 numbers', 'Unlimited Spotify streaming'],
  },
  {
    telco: 'M1',
    planName: 'Plan with Device',
    data: 12,
    talktime: 100,
    sms: 100,
    price: 30,
    pros: ['Free incoming calls', 'Unlimited free calls to 3 M1 numbers', 'Unlimited Spotify streaming'],
  },
  {
    telco: 'Zero1',
    planName: '3GB to Unlimited Data',
    data: 3,
    talktime: 200,
    sms: 200,
    price: 29.99,
    pros: ['Free incoming calls', 'Free caller ID', 'No pernalty for exceeding 3GB, only issue will be slower connection'],
  },
  {
    telco: 'Zero1',
    planName: '9GB to Unlimited Data',
    data: 9,
    talktime: 450,
    sms: 450,
    price: 39.90,
    pros: ['Free incoming calls', 'Free caller ID', 'No pernalty for exceeding 9GB, only issue will be slower connection'],
  },
  {
    telco: 'Zero1',
    planName: '1GB to Unlimited Data',
    data: 1,
    talktime: 200,
    sms: 200,
    price: 13.90,
    pros: ['Free incoming calls', 'Free caller ID', 'No pernalty for exceeding 1GB, only issue will be slower connection'],
  },
  {
    telco: 'Zero Mobile',
    planName: 'Zero X (New number)',
    data: 10000,
    talktime: 10000,
    sms: 10000,
    price: 59.95,
    cons: ['Usage in excess of 45GB/mth may be at controlled speeds'],
    pros: ['Free caller ID'],
  },
  {
    telco: 'Zero Mobile',
    planName: 'Zero X (Transfer number)',
    data: 10000,
    talktime: 10000,
    sms: 10000,
    price: 49.95,
    cons: ['Price returns to $59.95/mth after 1 year', 'Usage in excess of 45GB/mth may be at controlled speeds'],
    pros: ['Free caller ID', 'Free number porting'],
  },
  {
    telco: 'Zero Mobile',
    planName: 'Zero Xs (New number)',
    data: 10000,
    talktime: 100,
    sms: 100,
    price: 49.95,
    cons: ['Usage in excess of 45GB/mth may be at controlled speeds'],
    pros: ['Free caller ID'],
  },
  {
    telco: 'Zero Mobile',
    planName: 'Zero Xs (Transfer number)',
    data: 10000,
    talktime: 10000,
    sms: 10000,
    price: 39.95,
    cons: ['Price returns to $49.95/mth after 1 year', 'Usage in excess of 45GB/mth may be at controlled speeds'],
    pros: ['Free caller ID', 'Free number porting'],
  },
  {
    telco: 'MyRepublic',
    planName: 'Unlimited',
    data: 10000,
    talktime: 8000,
    sms: 8000,
    price: 48,
    cons: ['Usage in excess of 3GB/day may be at controlled speeds'],
    pros: ['Free caller ID', 'Free incoming calls'],
  },
  {
    telco: 'MyRepublic',
    planName: 'Smart 35',
    data: 12,
    talktime: 1000,
    sms: 1000,
    price: 35,
    cons: ['Usage in excess of 3GB/day may be at controlled speeds'],
    pros: ['3GB bonus data for broadband customers', 'Free caller ID', 'Free incoming calls'],
  },
  {
    telco: 'MyRepublic',
    planName: 'Uno 18',
    data: 1,
    talktime: 1000,
    sms: 1000,
    price: 18,
    pros: ['Free caller ID', 'Free incoming calls'],
  },
  {
    telco: 'MyRepublic',
    planName: 'Ultimate 80',
    data: 80,
    talktime: 1000,
    sms: 1000,
    price: 80,
    pros: ['Free caller ID', 'Free incoming calls'],
  },
  {
    telco: 'MyRepublic',
    planName: 'Mega 55',
    data: 18,
    talktime: 1000,
    sms: 1000,
    price: 55,
    pros: ['8GB bonus data for broadband customers', 'Free caller ID', 'Free incoming calls'],
  },
  {
    telco: 'MyRepublic',
    planName: 'Xtra 85',
    data: 30,
    talktime: 1000,
    sms: 1000,
    price: 85,
    pros: ['2GB Roam Like Home - Essential', 'Free caller ID', 'Free incoming calls'],
  },
  {
    telco: 'Starhub',
    planName: 'Giga!',
    data: 25,
    talktime: 1000,
    sms: 1000,
    price: 25,
    pros: ['Free caller ID', 'Free incoming calls'],
  },
  {
    telco: 'TPG',
    planName: 'SIM Only Mobile Plan',
    data: 10000,
    talktime: 20,
    sms: 20,
    price: 0,
    cons: ['Usage in excess of 2GB/day may be at controlled speeds'],
    pros: ['Free unlimited data roaming in Malaysia and Indonesia', 'Free incoming calls'],
  },
];

export default mobilePlanData;